#include "ucl.h"
#include "target.h"
#include "riscv_reg.h"
#include "output.h"

static int ORG;
static int FloatNum

static char *ASMTemplate[] = {
#define TEMPLATE(code, str) str,
#include "riscvlinux.tpl"
#undef TEMPLATE
};





static void Align(Symbol p) {
	int align = p->ty->align;
	if (ORG % align != 0) {
		Print(".align %d\n", align);	
		ORG = ALIGN(ORG, align);
	}
	ORG += p->ty->size;
}

void SetupRegisters(void) {
	riscvRegs[ZERO] = CreateReg("zero", NULL, ZERO);	
	riscvRegs[RA] = CreateReg("ra", "(ra)", RA);	
	riscvRegs[SP] = CreateReg("sp", "(sp)", SP);	
	riscvRegs[GP] = CreateReg("gp", "(gp)", GP);	
	riscvRegs[TP] = CreateReg("tp", "(tp)", TP);	
	riscvRegs[T0] = CreateReg("t0", "(t0)", T0);	
	riscvRegs[T1] = CreateReg("t1", "(t1)", T1);	
	riscvRegs[FP] = CreateReg("fp", "(fp)", FP);	
	riscvRegs[S1] = CreateReg("s1", "(s1)", S1);	
	riscvRegs[A0] = CreateReg("a0", "(a0)", A0);	
	riscvRegs[A1] = CreateReg("a1", "(a1)", A1);	
	riscvRegs[A2] = CreateReg("a2", "(a2)", A2);	
	riscvRegs[A3] = CreateReg("a3", "(a3)", A3);	
	riscvRegs[A4] = CreateReg("a4", "(a4)", A4);	
	riscvRegs[A5] = CreateReg("a5", "(a5)", A5);	
	riscvRegs[A6] = CreateReg("a6", "(a6)", A6);	
	riscvRegs[A7] = CreateReg("a7", "(a7)", A7);	
	riscvRegs[S2] = CreateReg("s2", "(s2)", S2);	
	riscvRegs[S3] = CreateReg("s3", "(s3)", S3);	
	riscvRegs[S4] = CreateReg("s4", "(s4)", S4);	
	riscvRegs[S5] = CreateReg("s5", "(s5)", S5);	
	riscvRegs[S6] = CreateReg("s6", "(s6)", S6);	
	riscvRegs[S7] = CreateReg("s7", "(s7)", S7);	
	riscvRegs[S8] = CreateReg("s8", "(s8)", S8);	
	riscvRegs[S9] = CreateReg("s9", "(s9)", S9);	
	riscvRegs[S10] = CreateReg("s10", "(s10)", S10);	
	riscvRegs[S11] = CreateReg("s11", "(s11)", S11);	
	riscvRegs[T3] = CreateReg("t3", "(t3)", T3);	
	riscvRegs[T4] = CreateReg("t4", "(t4)", T4);	
	riscvRegs[T5] = CreateReg("t5", "(t5)", T5);	
	riscvRegs[T6] = CreateReg("t6", "(t6)", T6);	
}


void BeginProgram() {
	int i;
	ORG = 0;
	FloatNum = TempNum = 0;
	for (i = ZERO; i <= T6; i++) {
		if (riscvRegs[i] != NULL) {
			riscvRegs[i]->link = NULL;
		}	
	}
	PutString("# Code auto-generated by ustc-sse-riscvcc\n\n");
}


void Segment(int seg) {
	if (seg == DATA) {
		PutString(".data\n\n");	
	} else if (seg == CODE) {
		PutString(".text\n\n");	
	}
}


Void DefineGlobal(Symbol p) {
	Align
}

